# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses. The 'type' key defines the base container
# image that will be used to run the application. There is a separate base
# container image for each primary language for the application,
# in multiple versions. Check the PHP documentation
# (https://docs.platform.sh/languages/php.html#supported-versions)
# to find the supported versions for the 'php' type.
type: "php:8.4"

# The following block defines a single writable directory, 'web/uploads'
# The 'source' specifies where the writable mount is. The 'local' source
# indicates that the mount point will point to a local directory on the
# application container. The 'source_path' specifies the subdirectory
# from within the source that the mount should point at.
mounts:
  "/var/cache": "shared:files/cache"
  "/var/log": "shared:files/log"
  "/var/sessions": "shared:files/sessions"
  "/public/uploads": "shared:files/uploads"
  "web/uploads":
    source: local
    source_path: uploads
  "/tmp/htmlpurifier":
    source: "tmp"
    source_path: "htmlpurifier"

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      index:
        - "index.php"

relationships:
  database: "db:mysql"
# The size of the persistent disk of the application (in MB).
disk: 2048
